name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Versão do Java
          java-package: jdk

      - name: Verificar versão do Java
        run: java -version

      - name: Verificar versão do Maven
        run: mvn -version

      - name: Instalar dependências
        run: mvn install -DskipTests

      - name: Executar testes
        run: mvn test