name: test ze

on:
  push:
    - feat-Github-Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.7
      - name: Maven Verify
        run: mvn clean compile