name: API Test Pipeline with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Install dependencies
        run: mvn install

      # Etapa de Testes (Health Check, Funcionais, etc.)
      - name: Run API Tests
        run: mvn clean test

      # Gerar o relatório Allure
      - name: Generate Allure Report
        run: mvn allure:report

      # Servir o relatório Allure localmente (para visualização, se necessário)
      - name: Serve Allure Report
        run: mvn allure:serve &

      # Publicar o relatório Allure no GitHub Pages
      - name: Upload Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin