name: Notify Discord

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificação para o Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          WORKFLOW_STATUS: ${{ job.status }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Actions",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [{
              "title": "🔔 Atualização no Repositório!",
              "description": "Um novo evento ocorreu no repositório.",
              "color": 3066993,
              "fields": [
                {
                  "name": "👤 Autor",
                  "value": "**${{ github.actor }}**"
                },
                {
                  "name": "📌 Evento",
                  "value": "${{ github.event_name }}"
                },
                {
                  "name": "📂 Repositório",
                  "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})"
                },
                {
                  "name": "📄 Último Commit",
                  "value": "[Clique aqui](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
                },
                {
                  "name": "🚦 Status do Workflow",
                  "value": "'"$WORKFLOW_STATUS"'"
                }
              ]
            }]
          }' \
          "$DISCORD_WEBHOOK"
