name: Maven Package

on:
  push:
    branches:
      - test-yml
  pull_request:
    branches:
      - test-yml
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Amazon Corretto JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Verify Java Version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file projetoResAula03/pom.xml

      - name: Run API Tests with Allure (Ignore Test Failures)
        run: mvn clean test --file projetoResAula03/pom.xml -Dallure.results.directory=projetoResAula03/allure-results -Dmaven.test.failure.ignore=true

      - name: Generate Allure Report
        run: mvn allure:report -f projetoResAula03/pom.xml -Dallure.results.directory=projetoResAula03/allure-results


      - name: Notify on Test Failures (if any)
        if: failure()
        run: |
          echo "Test failures detected!"
          # Send a notification (email, Slack, etc.)
          # Example for Slack:
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Test failures detected in the build!"}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
