name: allure-junit5-maven

on:
  push:
    branches-ignore:
      - '!main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install dependencies
        run: mvn -f projetoResAula03/pom.xml dependency:go-offline compile compiler:testCompile

      - name: Run Tests and Generate Allure Results
        run: mvn -f projetoResAula03/pom.xml clean test

      - name: List Allure results
        run: ls -R projetoResAula03/target/allure-results

      - name: Build Allure Report
        run: mvn -f projetoResAula03/pom.xml allure:report

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PAT_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/allure-report
